language: node_js
node_js:
- 8
install:
- cd functions
- npm install
before_deploy:
- cd ..
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "O+3MilXhS6oOL1ZUt6UqznD/2+6R0zZ6Rw3fDQANPiklUjmeAVNF/LT/qIsXlw3ewXHC/mSzKbVOsvdoPxp60MEE1A+8BxqbRUsCmIrBDCSncqdE5gFmxD99gdE7jWWfDEuVG+OsrpJN8arn5jj7kBR+VuwVOrvM6JVTQ5i3S1YAd+kZ7t8glO9BYG9U6ADBtSpOFpsE3lbOJxarWVhl00vzSxQOLc0KWV3rSdbNjRGSq6Emr6DzaValZHFodb6adBjie44+8dSmIeUzEVDhHy6/y5UAw5J+ldTSdcfQXUANwPXlQ+VNVNEFmwnd+hwzAD8EcECOdFbN82mnMwa+7ZnZlaU8RcPzBwOoddlGA04c3c1+phQws1QttDSFSg2mpdKCNHfuT0e6mG/j4+O3Dbq8abuKWI0vmntOM+Rh0g1cYKsyOQZJlXlNqYRGWCWWSA9UAEVd3cmuRkmX0m108Vvf5X9WAt0e6DIi1HOhzoJtaZa9e91xwxOi4pKhcAQzBitIi6O4w73N1tjDqB1L/RMglGcm5cxfgTFQCZCt0TYD+r9wL/92/ng816TbemWPqeyjgyqxzzMnSqF2od9hSRIwadCWO5guOsJtopD7+d7NfTui+ED77ti+H6Et7685rziyKUjinMQZqQqYsU+bSbQD/Q0gutpyNbrsLCHB398="
  on:
    branch: master

